name: Linters

on:
  pull_request:

  push:
    branches:
      - master
      - release_*

jobs:

  linters-tox:
    name: Tox
    strategy:
      matrix:
        tox_env:
          - bandit
          - pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test '${{ matrix.tox_env }}' with tox
      run: tox -e ${{ matrix.tox_env }}

  flake8:
    name: Flake8 for Python 3
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run flake8 for Python 3
        uses: containerbuildsystem/actions/flake8@master

  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: containerbuildsystem/actions/markdownlint@master
