name: Unittests

on:
  pull_request:

  push:
    branches:
      - master
      - release_*

jobs:
  test:
    name: Python ${{ matrix.env.python-version }}
    strategy:
      matrix:
          env:
            - python-version: "3.6"
              os: ubuntu-20.04
            - python-version: "3.7"
              os: ubuntu-22.04
            - python-version: "3.8"
              os: ubuntu-22.04
            - python-version: "3.9"
              os: ubuntu-22.04
            - python-version: "3.10"
              os: ubuntu-22.04
            - python-version: "3.11"
              os: ubuntu-22.04

    runs-on: ${{ matrix.env.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

    - name: Upload pytest html report
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        path: __pytest_reports/dfp-unit-tests.html
        name: dfp-unit-tests_python${{ matrix.env.python-version }}.html

    - name: Run coveralls-python
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: python${{ matrix.env.python-version }}
        COVERALLS_PARALLEL: true
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade coveralls
        coveralls --service=github

  coveralls-finish:
    name: Finish coveralls-python
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
